### ISSUE TITLE
Missing HTML lang attribute from home page

### ISSUE THREAD

**Issue by chinmaychahar** [bokeh/bokeh.org#23]

**Comment by bryevdv** [comment]
Hi @chinmaychahar You are correct that would be good to add. Note I have transferred this issue to a different repo https://github.com/bokeh/bokeh.org The "top level" site is separate from the docs in the main repo.

**Comment by bryevdv** [comment]
I think that updating the templates in this directory might be sufficient:

https://github.com/bokeh/bokeh.org/tree/main/_layouts

Note that that static https://bokeh.org site was very hastily put together by someone who does not have much website building experience (me) so there are probably lots of improvements that can be made. Any suggestions you have are very welcome!

**Comment by chinmaychahar** [comment]
@bryevdv should I update the website home page screengrab in the README.md too? The current one seems outdated

**Comment by bryevdv** [comment]
@chinmaychahar good eye! yes that would certainly be reasonable to update since the front page has changed

**Comment by chinmaychahar** [comment]
I'm trying to follow the instructions given in the readme and run the site locally using docker. 

```
C:\Users\Chinmay>docker --version
Docker version 20.10.23, build 7155243
```

However, I'm getting the following error while running `make serve`
```
PS C:\Users\Chinmay\bokeh.org> make serve
Launching dockerized site at http://localhost:4000
docker run --rm -v /cygdrive/c/Users/Chinmay/bokeh.org:/srv/jekyll -it -p 4000:4000 jekyll/jekyll:pages jekyll serve --incremental
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating...
jekyll 3.9.2 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
/usr/local/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir': Permission denied @ dir_s_mkdir - /srv/jekyll/_site (Errno::EACCES)
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:211:in `each'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/convertible.rb:226:in `write'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:209:in `block in write'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:332:in `block (2 levels) in each_site_file'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:331:in `each'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:331:in `block in each_site_file'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:330:in `each'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:330:in `each_site_file'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:208:in `write'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:73:in `process'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
        from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/gem/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
        from /usr/gem/bin/jekyll:25:in `load'
        from /usr/gem/bin/jekyll:25:in `<main>'
make: *** [Makefile:3: serve] Error 1
```

I tried to change the read/write permissions as well as manually creating the `_site` directory but nothing works. Any suggestions on what might be wrong? @bryevdv

**Comment by chinmaychahar** [comment]
Oh okay, I wonder if it might be due to some outdated requirements then. 
I'll try my best to see if I can solve it @bryevdv

**Comment by bryevdv** [comment]
👍 definitely we can update the README instructions too if that's the case

**Comment by chinmaychahar** [comment]
Yes, okay
